### ISSUE TITLE
Add binary release for electron

### ISSUE THREAD

**Issue by OpportunityLiu** [thefrontside/ctrlc-windows#35]
I'm trying to use this package with my electron app, got following error.

```
Error: Module did not self-register: '\\?\C:\package\node_modules\ctrlc-windows\dist\index.node'.
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\package\node_modules\ctrlc-windows\lib\index.js:4:41)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
```

**Comment by jbolda** [comment]
👋 

We just published a v2 that supports the node `n-api`, and I suspect that this might solve your issue. Would you mind giving it a try?

**Comment by cowboyd** [comment]
@OpportunityLiu it it should available if you update your package.json to point to `^2.0.0`

**Comment by OpportunityLiu** [comment]
It works with 2.0.0, thanks

**Comment by cowboyd** [comment]
Awesome! Let us know if there are any other issues.
